# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/book_series_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiBookSeriesItem(object):
    def setupUi(self, Book):
        Book.setObjectName("Book")
        Book.resize(996, 100)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Book.sizePolicy().hasHeightForWidth())
        Book.setSizePolicy(sizePolicy)
        Book.setMinimumSize(QtCore.QSize(750, 0))
        Book.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Book)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Book)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkboxBtn = QtWidgets.QPushButton(self.frame)
        self.checkboxBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.checkboxBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.checkboxBtn.setIconSize(QtCore.QSize(35, 35))
        self.checkboxBtn.setCheckable(True)
        self.checkboxBtn.setObjectName("checkboxBtn")
        self.horizontalLayout_2.addWidget(self.checkboxBtn)
        self.dataFrame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataFrame.sizePolicy().hasHeightForWidth())
        self.dataFrame.setSizePolicy(sizePolicy)
        self.dataFrame.setObjectName("dataFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dataFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.titleLabel = QtWidgets.QLabel(self.dataFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_6.addWidget(self.titleLabel)
        self.readerFrame = QtWidgets.QFrame(self.dataFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readerFrame.sizePolicy().hasHeightForWidth())
        self.readerFrame.setSizePolicy(sizePolicy)
        self.readerFrame.setObjectName("readerFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.readerFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.readerIcon = QtWidgets.QLabel(self.readerFrame)
        self.readerIcon.setText("")
        self.readerIcon.setPixmap(QtGui.QPixmap(":/other/mic.svg"))
        self.readerIcon.setObjectName("readerIcon")
        self.horizontalLayout_5.addWidget(self.readerIcon)
        self.readerLabel = QtWidgets.QLabel(self.readerFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.readerLabel.setFont(font)
        self.readerLabel.setObjectName("readerLabel")
        self.horizontalLayout_5.addWidget(self.readerLabel)
        self.horizontalLayout_6.addWidget(self.readerFrame)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.splitLine = QtWidgets.QFrame(self.dataFrame)
        self.splitLine.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splitLine.setObjectName("splitLine")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.splitLine)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line = QtWidgets.QFrame(self.splitLine)
        self.line.setAutoFillBackground(False)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout.addWidget(self.splitLine)
        self.downloadingFrame = QtWidgets.QFrame(self.dataFrame)
        self.downloadingFrame.setObjectName("downloadingFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.downloadingFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stopDownloadingBtn = QtWidgets.QPushButton(self.downloadingFrame)
        self.stopDownloadingBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.stopDownloadingBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/other/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.stopDownloadingBtn.setIcon(icon)
        self.stopDownloadingBtn.setIconSize(QtCore.QSize(25, 25))
        self.stopDownloadingBtn.setObjectName("stopDownloadingBtn")
        self.horizontalLayout_4.addWidget(self.stopDownloadingBtn)
        self.downloadingProgressBar = QtWidgets.QProgressBar(self.downloadingFrame)
        self.downloadingProgressBar.setMinimumSize(QtCore.QSize(400, 30))
        self.downloadingProgressBar.setProperty("value", 0)
        self.downloadingProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.downloadingProgressBar.setObjectName("downloadingProgressBar")
        self.horizontalLayout_4.addWidget(self.downloadingProgressBar)
        self.downloadingStatusLabel = QtWidgets.QLabel(self.downloadingFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.downloadingStatusLabel.setFont(font)
        self.downloadingStatusLabel.setObjectName("downloadingStatusLabel")
        self.horizontalLayout_4.addWidget(self.downloadingStatusLabel)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.downloadingFrame)
        self.horizontalLayout_2.addWidget(self.dataFrame)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Book)
        QtCore.QMetaObject.connectSlotsByName(Book)

    def retranslateUi(self, Book):
        _translate = QtCore.QCoreApplication.translate
        Book.setWindowTitle(_translate("Book", "Form"))
        self.titleLabel.setText(_translate("Book", "Название"))
        self.readerLabel.setText(_translate("Book", "reader"))
        self.downloadingStatusLabel.setText(_translate("Book", "Статус"))
