# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'books.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiLibraryView(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(788, 641)
        Form.setStyleSheet(
            "background-color: rgb(26, 25, 39);\n" "color: rgb(255, 255, 255);"
        )
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_31 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: white;")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_2.addWidget(self.label_31)
        spacerItem = QtWidgets.QSpacerItem(
            150,
            20,
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit.setStyleSheet(
            "border: 1px solid white;\n"
            "border-radius: 5px;\n"
            "background-color: rgb(73, 73, 91);\n"
            "color: white;"
        )
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_btn = QtWidgets.QToolButton(Form)
        self.search_btn.setStyleSheet(
            "QToolButton {\n"
            "    border: none;\n"
            "    background-color: rgba(255, 255, 255, 0);\n"
            "    padding: 3px;\n"
            "}\n"
            "QToolButton:hover:!pressed {\n"
            "    border: 0px solid;\n"
            "    background-color: qlineargradient(spread:pad, x1:1, y1:0.0401364, x2:0.572682, y2:0.38, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}"
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/menu/img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.search_btn.setIcon(icon)
        self.search_btn.setIconSize(QtCore.QSize(30, 30))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.add_book_btn = QtWidgets.QToolButton(Form)
        self.add_book_btn.setStyleSheet(
            "QToolButton {\n"
            "    border: none;\n"
            "    background-color: rgba(255, 255, 255, 0);\n"
            "    padding: 3px;\n"
            "}\n"
            "QToolButton:hover:!pressed {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.131, y1:0.0344546, x2:0.539, y2:0.521727, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}\n"
            "QToolTip {\n"
            "    background-color: #313040;\n"
            "    padding: 2px;\n"
            "    border-radius: 3px;\n"
            "    opacity: 200;\n"
            "}"
        )
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/menu/img/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.add_book_btn.setIcon(icon1)
        self.add_book_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_book_btn.setObjectName("add_book_btn")
        self.horizontalLayout.addWidget(self.add_book_btn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_21.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_21.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet(
            "QScrollArea {\n"
            "   border: none;\n"
            "}\n"
            " QScrollBar:vertical {\n"
            "    border: none;\n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    width: 8px;\n"
            "    margin: 15px 0px 15px 0 px;\n"
            " }\n"
            "QScrollBar::handle:vertical {\n"
            "    background-color: rgba(61, 81, 251, 100);\n"
            "    min-height: 30px;\n"
            "    border-radius: 4px;\n"
            "}\n"
            "QScrollBar::handle:vertical:hover{    \n"
            "    background-color:rgba(61, 81, 251, 200);\n"
            "}\n"
            "QScrollBar::handle:vertical:pressed {    \n"
            "    background-color: rgba(61, 81, 251, 255);\n"
            "}\n"
            "QScrollBar::sub-line:vertical {\n"
            "    height: 0px;\n"
            "}\n"
            "QScrollBar::add-line:vertical {\n"
            "    height: 0px;\n"
            "}\n"
            "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
            "    background: none;\n"
            "}\n"
            "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
            "    background: none;\n"
            "}"
        )
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 768, 563))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_21.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_31.setText(_translate("Form", "Мои книги"))
        self.search_btn.setText(_translate("Form", "..."))
        self.add_book_btn.setToolTip(_translate("Form", "Дабавить книгу"))
        self.add_book_btn.setText(_translate("Form", "..."))
