# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "QWidget {\n"
            "    color: rgb(142, 146, 151);\n"
            "}\n"
            "\n"
            "/* QFrame */\n"
            "QFrame {\n"
            "    border: none;\n"
            "}\n"
            "\n"
            "/*  BUTTONS */\n"
            "QPushButton {\n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    border-radius: 5px;    \n"
            "    border: none;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #34373C;\n"
            "    border-radius: 5px;    \n"
            "}\n"
            "QPushButton:pressed {    \n"
            "    background-color: #37393F;\n"
            "}\n"
            "\n"
            "/* LINE EDIT */\n"
            "QLineEdit {\n"
            "    background-color: rgb(64, 68, 75);\n"
            "    border-radius: 5px;\n"
            "    padding-left:3px;\n"
            "    border: none;\n"
            "}\n"
            "\n"
            "/* COMBOBOX */\n"
            "QComboBox {\n"
            "    background-color: rgb(64, 68, 75);\n"
            "    border-radius: 5px;\n"
            "    border: none;\n"
            "}\n"
            "QComboBox QAbstractItemView {\n"
            "      selection-background-color:  rgb(50, 53, 59);\n"
            "}\n"
            "QComboBox::drop-down {\n"
            "    border: none;\n"
            "}\n"
            "QComboBox::down-arrow {\n"
            "    image: url(:/other/angle_down.svg);\n"
            "    border: none;\n"
            "    width: 35px;\n"
            "    height: 35px;\n"
            "    padding-right: 20px;\n"
            "}\n"
            "\n"
            "/*  TOOLTIP */\n"
            "QToolTip {\n"
            "    border: none;\n"
            "    background-color: rgb(29, 30, 34);\n"
            "    border-left: 2px solid rgb(142, 146, 151);\n"
            "    color: rgb(142, 146, 151);\n"
            "    text-align: left;\n"
            "    padding: 4px;\n"
            "}\n"
            "\n"
            "/* SLIDER */\n"
            "QSlider {\n"
            "    background-color: rgb(41, 43, 47);\n"
            "}\n"
            "QSlider::groove:horizontal {\n"
            "    background: rgb(64, 68, 75);\n"
            "    border-radius: 1px;\n"
            "}\n"
            "QSlider::sub-page:horizontal {\n"
            "    background: rgb(142, 146, 151);\n"
            "    border-radius: 1px;\n"
            "    height: 40px;\n"
            "}\n"
            "QSlider::add-page:horizontal {\n"
            "    background: rgb(64, 68, 75);\n"
            "    border-radius: 1px;\n"
            "    height: 40px;\n"
            "}\n"
            "QSlider::handle:horizontal {\n"
            "    background: rgb(142, 146, 151);\n"
            "    border: 0px;\n"
            "    width: 5px;\n"
            "    margin-top: 0px;\n"
            "    margin-bottom: 0px;\n"
            "    border-radius: 1px;\n"
            "}\n"
            "\n"
            "/* TAB WIDGET */\n"
            "QTabWidget::pane {\n"
            "    border: none;\n"
            "} \n"
            "QTabBar::tab {\n"
            "    background: rgba(0, 0, 0, 0);\n"
            "    padding: 10px;\n"
            "    font-weight: normal;\n"
            "     border: none;\n"
            "} \n"
            "QTabBar::tab:selected {\n"
            "      background: rgba(0, 0, 0, 0);\n"
            "    border-top: 2px solid #fff;\n"
            "    font-weight: bold;\n"
            "    margin-bottom: -1px; \n"
            "}\n"
            "\n"
            "/*SCROLLBAR */\n"
            "QScrollArea {\n"
            "    border: none;\n"
            "}\n"
            "/* VERTICAL SCROLLBAR */\n"
            " QScrollBar:vertical {\n"
            "    border: none;\n"
            "    width: 8px;\n"
            "    margin: 15px 0px 15px 0 px;\n"
            " }\n"
            "/*  HANDLE BAR VERTICAL */\n"
            "QScrollBar::handle:vertical {\n"
            "    background-color: rgb(32, 34, 37);\n"
            "    min-height: 30px;\n"
            "    border-radius: 4px;\n"
            "}\n"
            "/* BTN TOP - SCROLLBAR */\n"
            "QScrollBar::sub-line:vertical {\n"
            "    height: 0px;\n"
            "}\n"
            "/* BTN BOTTOM - SCROLLBAR */\n"
            "QScrollBar::add-line:vertical {\n"
            "    height: 0px;\n"
            "}\n"
            "/* RESET ARROW */\n"
            "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
            "    background: rgb(46, 51, 56);\n"
            "    border-radius: 4px;\n"
            "}\n"
            "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
            "    background: rgb(46, 51, 56);\n"
            "    border-radius: 4px;\n"
            "}\n"
            "\n"
            "\n"
            "/* TOP FRAME */\n"
            "#topFrame {\n"
            "    background-color: rgb(32, 34, 37);\n"
            "}\n"
            "\n"
            "/*  MENU */\n"
            "#menuFrame {\n"
            "    background-color: rgb(32, 34, 37);\n"
            "}\n"
            "#menuFrame * {\n"
            "    text-align: left;\n"
            "}\n"
            "#menuFrame QPushButton {\n"
            "    padding: 6px 10px 6px 10px;\n"
            "}\n"
            "\n"
            "/*  CONTENT */\n"
            "#content, #stackedWidget, #libraryPage, #addBookPage, #searchResultPage, #settingsPage {\n"
            "    background-color: rgb(32, 34, 37);\n"
            "}\n"
            "#libraryPageContent, #addBookPageContent, #searchResultPageContent, #settingsPageContent {\n"
            "    background-color: rgb(54, 57, 63);\n"
            "    border-top-left-radius: 15px;\n"
            "}\n"
            "/* LIBRARY PAGE CONTENT */\n"
            "#libraryPageContent QTabWidget *{\n"
            "    background-color: rgb(54, 57, 63);\n"
            "}\n"
            "/* SEARCH RESULT PAGE CONTENT */\n"
            "#driversList, #driversListLayout {\n"
            "    background-color: rgb(47, 49, 54);\n"
            "    border-top-left-radius: 15px;\n"
            "    text-align: left;\n"
            "}\n"
            "\n"
            "/* LIBRARY FILTERS PANEL */\n"
            "#libraryFiltersPanel {\n"
            "    background-color: rgb(47, 49, 54);\n"
            "    border-top-left-radius: 15px;\n"
            "}\n"
            "#libraryFiltersPanel QFrame {\n"
            "    background-color: rgb(47, 49, 54);\n"
            "}\n"
            "#toggleBooksFilterPanelBtn {\n"
            "    background-color: rgb(54, 57, 63);\n"
            "    border-radius: 0px;\n"
            "    border-top-left-radius: 15px;\n"
            "}\n"
            "#toggleBooksFilterPanelBtn:hover {\n"
            "    background-color: rgb(50, 53, 59);\n"
            "}\n"
            "\n"
            "/*  CONTROL PANEL */\n"
            "#controlPanel, #controlPanel QFrame {\n"
            "    background-color: rgb(41, 43, 47);\n"
            "}"
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.topFrame = QtWidgets.QFrame(self.centralwidget)
        self.topFrame.setMinimumSize(QtCore.QSize(0, 28))
        self.topFrame.setMaximumSize(QtCore.QSize(16777215, 28))
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout_2.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo = QtWidgets.QLabel(self.topFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setObjectName("logo")
        self.horizontalLayout_2.addWidget(self.logo)
        self.topBtnFrame = QtWidgets.QFrame(self.topFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topBtnFrame.sizePolicy().hasHeightForWidth())
        self.topBtnFrame.setSizePolicy(sizePolicy)
        self.topBtnFrame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.topBtnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBtnFrame.setObjectName("topBtnFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topBtnFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.topBtnFrame)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.minimizeAppBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/other/dash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.minimizeAppBtn.setIcon(icon)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(14, 14))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout.addWidget(self.minimizeAppBtn)
        self.fullscreenAppBtn = QtWidgets.QPushButton(self.topBtnFrame)
        self.fullscreenAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.fullscreenAppBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.fullscreenAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/other/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.fullscreenAppBtn.setIcon(icon1)
        self.fullscreenAppBtn.setIconSize(QtCore.QSize(14, 14))
        self.fullscreenAppBtn.setObjectName("fullscreenAppBtn")
        self.horizontalLayout.addWidget(self.fullscreenAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.topBtnFrame)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.closeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/other/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.closeAppBtn.setIcon(icon2)
        self.closeAppBtn.setIconSize(QtCore.QSize(14, 14))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout.addWidget(self.closeAppBtn)
        self.horizontalLayout_2.addWidget(self.topBtnFrame)
        self.verticalLayout_4.addWidget(self.topFrame)
        self.centralFrame = QtWidgets.QFrame(self.centralwidget)
        self.centralFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centralFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralFrame.setObjectName("centralFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menuFrame = QtWidgets.QFrame(self.centralFrame)
        self.menuFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.menuFrame.setMaximumSize(QtCore.QSize(65, 16777215))
        self.menuFrame.setObjectName("menuFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menuFrame)
        self.verticalLayout.setContentsMargins(10, 8, 10, 8)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menuBtn = QtWidgets.QPushButton(self.menuFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.menuBtn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/other/angle_left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.menuBtn.setIcon(icon3)
        self.menuBtn.setIconSize(QtCore.QSize(25, 25))
        self.menuBtn.setObjectName("menuBtn")
        self.verticalLayout.addWidget(self.menuBtn)
        self.splitLine = QtWidgets.QFrame(self.menuFrame)
        self.splitLine.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splitLine.setObjectName("splitLine")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.splitLine)
        self.horizontalLayout_4.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line = QtWidgets.QFrame(self.splitLine)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setStyleSheet("background-color: rgb(45, 47, 50);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout.addWidget(self.splitLine)
        self.btnGroupFrame = QtWidgets.QFrame(self.menuFrame)
        self.btnGroupFrame.setObjectName("btnGroupFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.btnGroupFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.libraryBtn = QtWidgets.QPushButton(self.btnGroupFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.libraryBtn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/menu/book.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.libraryBtn.setIcon(icon4)
        self.libraryBtn.setIconSize(QtCore.QSize(25, 25))
        self.libraryBtn.setObjectName("libraryBtn")
        self.menuButtons = QtWidgets.QButtonGroup(MainWindow)
        self.menuButtons.setObjectName("menuButtons")
        self.menuButtons.addButton(self.libraryBtn)
        self.verticalLayout_2.addWidget(self.libraryBtn)
        self.addBookBtn = QtWidgets.QPushButton(self.btnGroupFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.addBookBtn.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/other/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.addBookBtn.setIcon(icon5)
        self.addBookBtn.setIconSize(QtCore.QSize(25, 25))
        self.addBookBtn.setObjectName("addBookBtn")
        self.menuButtons.addButton(self.addBookBtn)
        self.verticalLayout_2.addWidget(self.addBookBtn)
        self.verticalLayout.addWidget(self.btnGroupFrame)
        spacerItem = QtWidgets.QSpacerItem(
            20, 402, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem)
        self.btnGroupFrame_2 = QtWidgets.QFrame(self.menuFrame)
        self.btnGroupFrame_2.setObjectName("btnGroupFrame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.btnGroupFrame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dirWithBooksBtn = QtWidgets.QPushButton(self.btnGroupFrame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dirWithBooksBtn.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/menu/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.dirWithBooksBtn.setIcon(icon6)
        self.dirWithBooksBtn.setIconSize(QtCore.QSize(25, 25))
        self.dirWithBooksBtn.setObjectName("dirWithBooksBtn")
        self.menuButtons.addButton(self.dirWithBooksBtn)
        self.verticalLayout_5.addWidget(self.dirWithBooksBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.btnGroupFrame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.settingsBtn.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(":/menu/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.settingsBtn.setIcon(icon7)
        self.settingsBtn.setIconSize(QtCore.QSize(25, 25))
        self.settingsBtn.setObjectName("settingsBtn")
        self.menuButtons.addButton(self.settingsBtn)
        self.verticalLayout_5.addWidget(self.settingsBtn)
        self.verticalLayout.addWidget(self.btnGroupFrame_2)
        self.horizontalLayout_3.addWidget(self.menuFrame)
        self.contentBox = QtWidgets.QFrame(self.centralFrame)
        self.contentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.content = QtWidgets.QFrame(self.contentBox)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setLineWidth(1)
        self.content.setObjectName("content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.libraryPage = QtWidgets.QWidget()
        self.libraryPage.setObjectName("libraryPage")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.libraryPage)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.libraryPageContent = QtWidgets.QFrame(self.libraryPage)
        self.libraryPageContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.libraryPageContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.libraryPageContent.setObjectName("libraryPageContent")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.libraryPageContent)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.libraryFiltersPanel = QtWidgets.QFrame(self.libraryPageContent)
        self.libraryFiltersPanel.setMinimumSize(QtCore.QSize(225, 0))
        self.libraryFiltersPanel.setMaximumSize(QtCore.QSize(25, 16777215))
        self.libraryFiltersPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.libraryFiltersPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.libraryFiltersPanel.setObjectName("libraryFiltersPanel")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.libraryFiltersPanel)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.toggleBooksFilterPanelBtn = QtWidgets.QPushButton(self.libraryFiltersPanel)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.toggleBooksFilterPanelBtn.sizePolicy().hasHeightForWidth()
        )
        self.toggleBooksFilterPanelBtn.setSizePolicy(sizePolicy)
        self.toggleBooksFilterPanelBtn.setMinimumSize(QtCore.QSize(25, 0))
        self.toggleBooksFilterPanelBtn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.toggleBooksFilterPanelBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(":/other/angle_right.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.toggleBooksFilterPanelBtn.setIcon(icon8)
        self.toggleBooksFilterPanelBtn.setIconSize(QtCore.QSize(14, 14))
        self.toggleBooksFilterPanelBtn.setObjectName("toggleBooksFilterPanelBtn")
        self.horizontalLayout_15.addWidget(self.toggleBooksFilterPanelBtn)
        self.libraryFiltersFrame = QtWidgets.QFrame(self.libraryFiltersPanel)
        self.libraryFiltersFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.libraryFiltersFrame.setMaximumSize(QtCore.QSize(0, 16777215))
        self.libraryFiltersFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.libraryFiltersFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.libraryFiltersFrame.setObjectName("libraryFiltersFrame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.libraryFiltersFrame)
        self.verticalLayout_16.setSpacing(20)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.searchField = QtWidgets.QFrame(self.libraryFiltersFrame)
        self.searchField.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 0px;\n"
            "    border-top-left-radius: 5px;\n"
            "    border-bottom-left-radius: 5px;\n"
            "}\n"
            "QPushButton {\n"
            "    background-color: rgb(64, 68, 75);\n"
            "    border-radius: 0px;\n"
            "    border-top-right-radius: 5px;\n"
            "    border-bottom-right-radius: 5px;\n"
            "    border-left: 1px solid #8E9297;\n"
            "    padding-left: 2px;\n"
            "    padding-right: 2px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(50, 53, 59);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    margin-bottom: -1px;\n"
            "}"
        )
        self.searchField.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchField.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchField.setObjectName("searchField")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.searchField)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.searchBookLineEdit = QtWidgets.QLineEdit(self.searchField)
        self.searchBookLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.searchBookLineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.searchBookLineEdit.setFont(font)
        self.searchBookLineEdit.setText("")
        self.searchBookLineEdit.setObjectName("searchBookLineEdit")
        self.horizontalLayout_16.addWidget(self.searchBookLineEdit)
        self.searchBookBtn = QtWidgets.QPushButton(self.searchField)
        self.searchBookBtn.setMinimumSize(QtCore.QSize(35, 35))
        self.searchBookBtn.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.searchBookBtn.setFont(font)
        self.searchBookBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap(":/menu/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.searchBookBtn.setIcon(icon9)
        self.searchBookBtn.setIconSize(QtCore.QSize(28, 28))
        self.searchBookBtn.setObjectName("searchBookBtn")
        self.horizontalLayout_16.addWidget(self.searchBookBtn)
        self.verticalLayout_16.addWidget(self.searchField)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.libraryFiltersFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.sortByFrame = QtWidgets.QFrame(self.libraryFiltersFrame)
        self.sortByFrame.setStyleSheet(
            "QComboBox {\n"
            "    border-radius: 0px;\n"
            "    border-top-left-radius: 5px;\n"
            "    border-bottom-left-radius: 5px;\n"
            "}\n"
            "QPushButton {\n"
            "    background-color: rgb(64, 68, 75);\n"
            "    border-radius: 0px;\n"
            "    border-top-right-radius: 5px;\n"
            "    border-bottom-right-radius: 5px;\n"
            "    border-left: 1px solid #8E9297;\n"
            "    padding-left: 2px;\n"
            "    padding-right: 2px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(50, 53, 59);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    margin-bottom: -1px;\n"
            "}"
        )
        self.sortByFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sortByFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sortByFrame.setObjectName("sortByFrame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.sortByFrame)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.sortBy = QtWidgets.QComboBox(self.sortByFrame)
        self.sortBy.setMinimumSize(QtCore.QSize(0, 35))
        self.sortBy.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sortBy.setFont(font)
        self.sortBy.setObjectName("sortBy")
        self.sortBy.addItem("")
        self.sortBy.addItem("")
        self.sortBy.addItem("")
        self.horizontalLayout_17.addWidget(self.sortBy)
        self.invertSortBtn = QtWidgets.QPushButton(self.sortByFrame)
        self.invertSortBtn.setMinimumSize(QtCore.QSize(35, 35))
        self.invertSortBtn.setMaximumSize(QtCore.QSize(35, 35))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap(":/other/sort_down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.invertSortBtn.setIcon(icon10)
        self.invertSortBtn.setIconSize(QtCore.QSize(28, 28))
        self.invertSortBtn.setObjectName("invertSortBtn")
        self.horizontalLayout_17.addWidget(self.invertSortBtn)
        self.verticalLayout_8.addWidget(self.sortByFrame)
        self.verticalLayout_16.addLayout(self.verticalLayout_8)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_3 = QtWidgets.QLabel(self.libraryFiltersFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_15.addWidget(self.label_3)
        self.sortAuthorFrame = QtWidgets.QFrame(self.libraryFiltersFrame)
        self.sortAuthorFrame.setStyleSheet(
            "QComboBox {\n"
            "    border-radius: 0px;\n"
            "    border-top-left-radius: 5px;\n"
            "    border-bottom-left-radius: 5px;\n"
            "}\n"
            "QPushButton {\n"
            "    background-color: rgb(64, 68, 75);\n"
            "    border-radius: 0px;\n"
            "    border-top-right-radius: 5px;\n"
            "    border-bottom-right-radius: 5px;\n"
            "    border-left: 1px solid #8E9297;\n"
            "    padding-left: 2px;\n"
            "    padding-right: 2px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(50, 53, 59);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    margin-bottom: -1px;\n"
            "}"
        )
        self.sortAuthorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sortAuthorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sortAuthorFrame.setObjectName("sortAuthorFrame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.sortAuthorFrame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.sortAuthor = QtWidgets.QComboBox(self.sortAuthorFrame)
        self.sortAuthor.setMinimumSize(QtCore.QSize(0, 35))
        self.sortAuthor.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sortAuthor.setFont(font)
        self.sortAuthor.setObjectName("sortAuthor")
        self.sortAuthor.addItem("")
        self.horizontalLayout_18.addWidget(self.sortAuthor)
        self.clearSortAuthorBtn = QtWidgets.QPushButton(self.sortAuthorFrame)
        self.clearSortAuthorBtn.setMinimumSize(QtCore.QSize(35, 35))
        self.clearSortAuthorBtn.setMaximumSize(QtCore.QSize(35, 35))
        self.clearSortAuthorBtn.setIcon(icon2)
        self.clearSortAuthorBtn.setIconSize(QtCore.QSize(28, 28))
        self.clearSortAuthorBtn.setObjectName("clearSortAuthorBtn")
        self.horizontalLayout_18.addWidget(self.clearSortAuthorBtn)
        self.verticalLayout_15.addWidget(self.sortAuthorFrame)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 533, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_16.addItem(spacerItem1)
        self.horizontalLayout_15.addWidget(self.libraryFiltersFrame)
        self.horizontalLayout_19.addWidget(self.libraryFiltersPanel)
        self.libraryBox = QtWidgets.QFrame(self.libraryPageContent)
        self.libraryBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.libraryBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.libraryBox.setObjectName("libraryBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.libraryBox)
        self.verticalLayout_3.setContentsMargins(8, 10, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.libraryBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.libraryFrame = QtWidgets.QFrame(self.libraryBox)
        self.libraryFrame.setStyleSheet(
            "#libraryFrame {\n"
            "    border-top: 2px solid rgb(41, 43, 47);\n"
            "    border-radius: 2px;\n"
            "}"
        )
        self.libraryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.libraryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.libraryFrame.setObjectName("libraryFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.libraryFrame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.library = QtWidgets.QTabWidget(self.libraryFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.library.setFont(font)
        self.library.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.library.setObjectName("library")
        self.allBooksPage = QtWidgets.QWidget()
        self.allBooksPage.setObjectName("allBooksPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.allBooksPage)
        self.verticalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.allBooksContainer = QtWidgets.QScrollArea(self.allBooksPage)
        self.allBooksContainer.setWidgetResizable(True)
        self.allBooksContainer.setObjectName("allBooksContainer")
        self.allBooksLayout = QtWidgets.QWidget()
        self.allBooksLayout.setGeometry(QtCore.QRect(0, 0, 677, 480))
        self.allBooksLayout.setObjectName("allBooksLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.allBooksLayout)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_4 = QtWidgets.QFrame(self.allBooksLayout)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_4.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.allBooksLayout)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_3.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(-40, -10, 598, 150))
        self.frame.setMinimumSize(QtCore.QSize(0, 150))
        self.frame.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.allBooksLayout)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_2.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_10.addWidget(self.frame_2)
        self.allBooksContainer.setWidget(self.allBooksLayout)
        self.verticalLayout_9.addWidget(self.allBooksContainer)
        self.library.addTab(self.allBooksPage, "")
        self.inProsessBooksPage = QtWidgets.QWidget()
        self.inProsessBooksPage.setObjectName("inProsessBooksPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.inProsessBooksPage)
        self.verticalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.inProgressBooksContainer = QtWidgets.QScrollArea(self.inProsessBooksPage)
        self.inProgressBooksContainer.setWidgetResizable(True)
        self.inProgressBooksContainer.setObjectName("inProgressBooksContainer")
        self.inProgressBooksLayout = QtWidgets.QWidget()
        self.inProgressBooksLayout.setGeometry(QtCore.QRect(0, 0, 685, 469))
        self.inProgressBooksLayout.setObjectName("inProgressBooksLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.inProgressBooksLayout)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_5 = QtWidgets.QFrame(self.inProgressBooksLayout)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_5.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.inProgressBooksLayout)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_6.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_11.addWidget(self.frame_6)
        self.inProgressBooksContainer.setWidget(self.inProgressBooksLayout)
        self.verticalLayout_12.addWidget(self.inProgressBooksContainer)
        self.library.addTab(self.inProsessBooksPage, "")
        self.listenedBooksPage = QtWidgets.QWidget()
        self.listenedBooksPage.setObjectName("listenedBooksPage")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.listenedBooksPage)
        self.verticalLayout_14.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.listenedBooksContainer = QtWidgets.QScrollArea(self.listenedBooksPage)
        self.listenedBooksContainer.setWidgetResizable(True)
        self.listenedBooksContainer.setObjectName("listenedBooksContainer")
        self.listenedBooksLayout = QtWidgets.QWidget()
        self.listenedBooksLayout.setGeometry(QtCore.QRect(0, 0, 677, 480))
        self.listenedBooksLayout.setObjectName("listenedBooksLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.listenedBooksLayout)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_10 = QtWidgets.QFrame(self.listenedBooksLayout)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_10.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_13.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.listenedBooksLayout)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_11.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_13.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.listenedBooksLayout)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_12.setStyleSheet(
            "background-color: rgb(47, 49, 54);\n" "border-radius:10px;"
        )
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_13.addWidget(self.frame_12)
        self.listenedBooksContainer.setWidget(self.listenedBooksLayout)
        self.verticalLayout_14.addWidget(self.listenedBooksContainer)
        self.library.addTab(self.listenedBooksPage, "")
        self.horizontalLayout_13.addWidget(self.library)
        self.verticalLayout_3.addWidget(self.libraryFrame)
        self.horizontalLayout_19.addWidget(self.libraryBox)
        self.horizontalLayout_21.addWidget(self.libraryPageContent)
        self.stackedWidget.addWidget(self.libraryPage)
        self.addBookPage = QtWidgets.QWidget()
        self.addBookPage.setObjectName("addBookPage")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.addBookPage)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.addBookPageContent = QtWidgets.QFrame(self.addBookPage)
        self.addBookPageContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addBookPageContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addBookPageContent.setObjectName("addBookPageContent")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.addBookPageContent)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem2 = QtWidgets.QSpacerItem(
            268, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_23.addItem(spacerItem2)
        self.searchForm = QtWidgets.QFrame(self.addBookPageContent)
        self.searchForm.setMinimumSize(QtCore.QSize(350, 0))
        self.searchForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchForm.setObjectName("searchForm")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.searchForm)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_17.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.searchForm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_17.addWidget(self.label_4)
        self.searchField_2 = QtWidgets.QFrame(self.searchForm)
        self.searchField_2.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 0px;\n"
            "    border-top-left-radius: 5px;\n"
            "    border-bottom-left-radius: 5px;\n"
            "}\n"
            "QPushButton {\n"
            "    background-color: rgb(64, 68, 75);\n"
            "    border-radius: 0px;\n"
            "    border-top-right-radius: 5px;\n"
            "    border-bottom-right-radius: 5px;\n"
            "    border-left: 1px solid #8E9297;\n"
            "    padding-left: 2px;\n"
            "    padding-right: 2px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(50, 53, 59);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    margin-bottom: -1px;\n"
            "}"
        )
        self.searchField_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchField_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchField_2.setObjectName("searchField_2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.searchField_2)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.searchNewBookLineEdit = QtWidgets.QLineEdit(self.searchField_2)
        self.searchNewBookLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.searchNewBookLineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.searchNewBookLineEdit.setFont(font)
        self.searchNewBookLineEdit.setText("")
        self.searchNewBookLineEdit.setObjectName("searchNewBookLineEdit")
        self.horizontalLayout_22.addWidget(self.searchNewBookLineEdit)
        self.searchNewBookBtn = QtWidgets.QPushButton(self.searchField_2)
        self.searchNewBookBtn.setMinimumSize(QtCore.QSize(35, 35))
        self.searchNewBookBtn.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.searchNewBookBtn.setFont(font)
        self.searchNewBookBtn.setText("")
        self.searchNewBookBtn.setIcon(icon9)
        self.searchNewBookBtn.setIconSize(QtCore.QSize(28, 28))
        self.searchNewBookBtn.setObjectName("searchNewBookBtn")
        self.horizontalLayout_22.addWidget(self.searchNewBookBtn)
        self.verticalLayout_17.addWidget(self.searchField_2)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_17.addItem(spacerItem4)
        self.horizontalLayout_23.addWidget(self.searchForm)
        spacerItem5 = QtWidgets.QSpacerItem(
            267, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_23.addItem(spacerItem5)
        self.horizontalLayout_14.addWidget(self.addBookPageContent)
        self.stackedWidget.addWidget(self.addBookPage)
        self.noSearchResultPage = QtWidgets.QWidget()
        self.noSearchResultPage.setObjectName("noSearchResultPage")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.noSearchResultPage)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.noSearchResultPageContent = QtWidgets.QFrame(self.noSearchResultPage)
        self.noSearchResultPageContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.noSearchResultPageContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.noSearchResultPageContent.setObjectName("noSearchResultPageContent")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.noSearchResultPageContent)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem6 = QtWidgets.QSpacerItem(
            408, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_25.addItem(spacerItem6)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem7 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_18.addItem(spacerItem7)
        self.noSearchResultReasonLabel = QtWidgets.QLabel(
            self.noSearchResultPageContent
        )
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.noSearchResultReasonLabel.setFont(font)
        self.noSearchResultReasonLabel.setObjectName("noSearchResultReasonLabel")
        self.verticalLayout_18.addWidget(self.noSearchResultReasonLabel)
        spacerItem8 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_18.addItem(spacerItem8)
        self.horizontalLayout_25.addLayout(self.verticalLayout_18)
        spacerItem9 = QtWidgets.QSpacerItem(
            407, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_25.addItem(spacerItem9)
        self.horizontalLayout_24.addWidget(self.noSearchResultPageContent)
        self.stackedWidget.addWidget(self.noSearchResultPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.settingsPage)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.settingsPageContent = QtWidgets.QFrame(self.settingsPage)
        self.settingsPageContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsPageContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsPageContent.setObjectName("settingsPageContent")
        self.horizontalLayout_20.addWidget(self.settingsPageContent)
        self.stackedWidget.addWidget(self.settingsPage)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_7.addWidget(self.content)
        self.controlPanel = QtWidgets.QFrame(self.contentBox)
        self.controlPanel.setMinimumSize(QtCore.QSize(0, 75))
        self.controlPanel.setMaximumSize(QtCore.QSize(16777215, 75))
        self.controlPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlPanel.setObjectName("controlPanel")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.controlPanel)
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bookPreview = QtWidgets.QFrame(self.controlPanel)
        self.bookPreview.setMinimumSize(QtCore.QSize(150, 60))
        self.bookPreview.setMaximumSize(QtCore.QSize(340, 60))
        self.bookPreview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bookPreview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bookPreview.setObjectName("bookPreview")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bookPreview)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bookCover = QtWidgets.QLabel(self.bookPreview)
        self.bookCover.setMinimumSize(QtCore.QSize(60, 60))
        self.bookCover.setMaximumSize(QtCore.QSize(60, 60))
        self.bookCover.setStyleSheet("background-color: rgb(130, 130, 130);")
        self.bookCover.setText("")
        self.bookCover.setObjectName("bookCover")
        self.horizontalLayout_6.addWidget(self.bookCover)
        self.bookTitle = QtWidgets.QFrame(self.bookPreview)
        self.bookTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.bookTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bookTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bookTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bookTitle.setObjectName("bookTitle")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.bookTitle)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bookNameLabel = QtWidgets.QLabel(self.bookTitle)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bookNameLabel.setFont(font)
        self.bookNameLabel.setObjectName("bookNameLabel")
        self.verticalLayout_6.addWidget(self.bookNameLabel)
        self.bookAuthorLabel = QtWidgets.QLabel(self.bookTitle)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bookAuthorLabel.setFont(font)
        self.bookAuthorLabel.setObjectName("bookAuthorLabel")
        self.verticalLayout_6.addWidget(self.bookAuthorLabel)
        spacerItem10 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_6.addItem(spacerItem10)
        self.horizontalLayout_6.addWidget(self.bookTitle)
        self.horizontalLayout_7.addWidget(self.bookPreview)
        self.playPauseBtn = QtWidgets.QPushButton(self.controlPanel)
        self.playPauseBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.playPauseBtn.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.playPauseBtn.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap(":/other/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.playPauseBtn.setIcon(icon11)
        self.playPauseBtn.setIconSize(QtCore.QSize(40, 40))
        self.playPauseBtn.setObjectName("playPauseBtn")
        self.controlPanelButtons = QtWidgets.QButtonGroup(MainWindow)
        self.controlPanelButtons.setObjectName("controlPanelButtons")
        self.controlPanelButtons.addButton(self.playPauseBtn)
        self.horizontalLayout_7.addWidget(self.playPauseBtn)
        spacerItem11 = QtWidgets.QSpacerItem(
            674, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_7.addItem(spacerItem11)
        self.toolsFrame = QtWidgets.QFrame(self.controlPanel)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolsFrame.sizePolicy().hasHeightForWidth())
        self.toolsFrame.setSizePolicy(sizePolicy)
        self.toolsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolsFrame.setObjectName("toolsFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.toolsFrame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.speedBox = QtWidgets.QFrame(self.toolsFrame)
        self.speedBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.speedBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.speedBox.setObjectName("speedBox")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.speedBox)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.speedBtn = QtWidgets.QPushButton(self.speedBox)
        self.speedBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.speedBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.speedBtn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(
            QtGui.QPixmap(":/other/watch.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.speedBtn.setIcon(icon12)
        self.speedBtn.setIconSize(QtCore.QSize(28, 28))
        self.speedBtn.setObjectName("speedBtn")
        self.controlPanelButtons.addButton(self.speedBtn)
        self.horizontalLayout_11.addWidget(self.speedBtn)
        self.speedFrame = QtWidgets.QFrame(self.speedBox)
        self.speedFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.speedFrame.setMaximumSize(QtCore.QSize(0, 16777215))
        self.speedFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.speedFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.speedFrame.setObjectName("speedFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.speedFrame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.speedSlider = QtWidgets.QSlider(self.speedFrame)
        self.speedSlider.setMinimumSize(QtCore.QSize(80, 35))
        self.speedSlider.setMaximumSize(QtCore.QSize(80, 35))
        self.speedSlider.setStyleSheet("")
        self.speedSlider.setMaximum(100)
        self.speedSlider.setProperty("value", 50)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.horizontalLayout_12.addWidget(self.speedSlider)
        self.speedLabel = QtWidgets.QLabel(self.speedFrame)
        self.speedLabel.setObjectName("speedLabel")
        self.horizontalLayout_12.addWidget(self.speedLabel)
        self.horizontalLayout_11.addWidget(self.speedFrame)
        self.horizontalLayout_8.addWidget(self.speedBox)
        self.volumeBox = QtWidgets.QFrame(self.toolsFrame)
        self.volumeBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.volumeBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.volumeBox.setObjectName("volumeBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.volumeBox)
        self.horizontalLayout_10.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.volumeBtn = QtWidgets.QPushButton(self.volumeBox)
        self.volumeBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.volumeBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.volumeBtn.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(
            QtGui.QPixmap(":/volume/medium_volume.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.volumeBtn.setIcon(icon13)
        self.volumeBtn.setIconSize(QtCore.QSize(28, 28))
        self.volumeBtn.setObjectName("volumeBtn")
        self.controlPanelButtons.addButton(self.volumeBtn)
        self.horizontalLayout_10.addWidget(self.volumeBtn)
        self.volumeFrame = QtWidgets.QFrame(self.volumeBox)
        self.volumeFrame.setMaximumSize(QtCore.QSize(0, 16777215))
        self.volumeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.volumeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.volumeFrame.setObjectName("volumeFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.volumeFrame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.volumeSlider = QtWidgets.QSlider(self.volumeFrame)
        self.volumeSlider.setMinimumSize(QtCore.QSize(80, 35))
        self.volumeSlider.setMaximumSize(QtCore.QSize(80, 35))
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 50)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_9.addWidget(self.volumeSlider)
        self.volumeLabel = QtWidgets.QLabel(self.volumeFrame)
        self.volumeLabel.setObjectName("volumeLabel")
        self.horizontalLayout_9.addWidget(self.volumeLabel)
        self.horizontalLayout_10.addWidget(self.volumeFrame)
        self.horizontalLayout_8.addWidget(self.volumeBox)
        self.overlayBtn = QtWidgets.QPushButton(self.toolsFrame)
        self.overlayBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.overlayBtn.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.overlayBtn.setFont(font)
        self.overlayBtn.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(
            QtGui.QPixmap(":/other/overlay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.overlayBtn.setIcon(icon14)
        self.overlayBtn.setIconSize(QtCore.QSize(28, 28))
        self.overlayBtn.setObjectName("overlayBtn")
        self.controlPanelButtons.addButton(self.overlayBtn)
        self.horizontalLayout_8.addWidget(self.overlayBtn)
        self.horizontalLayout_7.addWidget(self.toolsFrame)
        self.resizeWidgetFrame = QtWidgets.QFrame(self.controlPanel)
        self.resizeWidgetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resizeWidgetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resizeWidgetFrame.setObjectName("resizeWidgetFrame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.resizeWidgetFrame)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem12 = QtWidgets.QSpacerItem(
            20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_19.addItem(spacerItem12)
        self.label_5 = QtWidgets.QLabel(self.resizeWidgetFrame)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setStyleSheet("image: url(:/other/resize_bottom_right.svg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_19.addWidget(self.label_5)
        self.horizontalLayout_7.addWidget(self.resizeWidgetFrame)
        self.verticalLayout_7.addWidget(self.controlPanel)
        self.horizontalLayout_3.addWidget(self.contentBox)
        self.verticalLayout_4.addWidget(self.centralFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.library.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AB Player"))
        self.logo.setText(_translate("MainWindow", "AB Player"))
        self.menuBtn.setText(_translate("MainWindow", " Скрыть меню"))
        self.libraryBtn.setText(_translate("MainWindow", " Мои книги"))
        self.addBookBtn.setText(_translate("MainWindow", " Новая книга"))
        self.dirWithBooksBtn.setText(_translate("MainWindow", " Папка с книгами"))
        self.settingsBtn.setText(_translate("MainWindow", " Настройки"))
        self.searchBookLineEdit.setPlaceholderText(
            _translate("MainWindow", "Найти в библиотеке")
        )
        self.label_2.setText(_translate("MainWindow", "Сортировать по"))
        self.sortBy.setItemText(0, _translate("MainWindow", "Дате добавления"))
        self.sortBy.setItemText(1, _translate("MainWindow", "Названию"))
        self.sortBy.setItemText(2, _translate("MainWindow", "Автору"))
        self.label_3.setText(_translate("MainWindow", "Автор"))
        self.sortAuthor.setItemText(0, _translate("MainWindow", "Все"))
        self.label.setText(_translate("MainWindow", "Библиотека"))
        self.library.setTabText(
            self.library.indexOf(self.allBooksPage), _translate("MainWindow", "Все")
        )
        self.library.setTabText(
            self.library.indexOf(self.inProsessBooksPage),
            _translate("MainWindow", "В процессе"),
        )
        self.library.setTabText(
            self.library.indexOf(self.listenedBooksPage),
            _translate("MainWindow", "Прослушанные"),
        )
        self.label_4.setText(_translate("MainWindow", "Поиск книги"))
        self.searchNewBookLineEdit.setPlaceholderText(
            _translate("MainWindow", "Введите название книги или вставьте ссылку")
        )
        self.noSearchResultReasonLabel.setText(_translate("MainWindow", "текст"))
        self.bookNameLabel.setText(_translate("MainWindow", "Название"))
        self.bookAuthorLabel.setText(_translate("MainWindow", "Автор"))
        self.speedBtn.setToolTip(_translate("MainWindow", "Скорость воспроизведения"))
        self.speedLabel.setText(_translate("MainWindow", "50%"))
        self.volumeBtn.setToolTip(_translate("MainWindow", "Громкость"))
        self.volumeLabel.setText(_translate("MainWindow", "50%"))
        self.overlayBtn.setToolTip(_translate("MainWindow", "Открыть поверх всех окон"))
