# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 564)
        MainWindow.setStyleSheet(
            "background-color: rgb(26, 25, 39);\n" "color: rgb(255, 255, 255);"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setMinimumSize(QtCore.QSize(250, 0))
        self.menu_frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.menu_frame.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.506, y1:0.0166818, x2:0.511, y2:1, stop:0 rgba(26, 25, 39, 255), stop:1 rgba(49, 48, 64, 255));"
        )
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.menu_frame)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_8.setStyleSheet(
            "background-color: rgba(255, 255, 255, 0);\n" "text-align: left;"
        )
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.menu_btn = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.menu_btn.setFont(font)
        self.menu_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_btn.setStyleSheet(
            "QPushButton {\n"
            "    padding:10px;\n"
            "    border-radius: 3px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.982955, y1:0.739, x2:0.2545, y2:0.602, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}\n"
            "QPushButton:checked {\n"
            "    background-color: rgba(130, 134, 156, 150);\n"
            "    border-radius: 10px;\n"
            "}"
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/menu/img/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.menu_btn.setIcon(icon)
        self.menu_btn.setIconSize(QtCore.QSize(25, 25))
        self.menu_btn.setCheckable(True)
        self.menu_btn.setObjectName("menu_btn")
        self.verticalLayout_8.addWidget(self.menu_btn)
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        self.frame_6.setStyleSheet(
            "background-color: rgba(255, 255, 255, 0);\n" "align: left;"
        )
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.my_books_btn = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.my_books_btn.setFont(font)
        self.my_books_btn.setStyleSheet(
            "QPushButton {\n"
            "    padding:10px;\n"
            "    border-radius: 3px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.886, y1:0.483, x2:0.107318, y2:0.647, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}\n"
            "QPushButton:checked {\n"
            "    background-color: qlineargradient(spread:pad, x1:1, y1:0.506045, x2:0.743545, y2:0.499, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}"
        )
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/menu/img/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.my_books_btn.setIcon(icon1)
        self.my_books_btn.setIconSize(QtCore.QSize(25, 25))
        self.my_books_btn.setCheckable(True)
        self.my_books_btn.setObjectName("my_books_btn")
        self.verticalLayout_6.addWidget(self.my_books_btn)
        self.my_favorite_btn = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.my_favorite_btn.setFont(font)
        self.my_favorite_btn.setStyleSheet(
            "QPushButton {\n"
            "    padding:10px;\n"
            "    border-radius: 3px;\n"
            "}\n"
            "QPushButton:hover {;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.948955, y1:0.54, x2:0.596227, y2:0.545, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}\n"
            "QPushButton:checked {\n"
            "    background-color: qlineargradient(spread:pad, x1:1, y1:0.506045, x2:0.743545, y2:0.499, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}"
        )
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/menu/img/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.my_favorite_btn.setIcon(icon2)
        self.my_favorite_btn.setIconSize(QtCore.QSize(25, 25))
        self.my_favorite_btn.setCheckable(True)
        self.my_favorite_btn.setObjectName("my_favorite_btn")
        self.verticalLayout_6.addWidget(self.my_favorite_btn)
        self.search_btn = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet(
            "QPushButton {\n"
            "    padding:10px;\n"
            "    border-radius: 3px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.755773, y1:0.841, x2:0.136, y2:0.636136, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}\n"
            "QPushButton:checked {\n"
            "    background-color: qlineargradient(spread:pad, x1:1, y1:0.506045, x2:0.743545, y2:0.499, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}"
        )
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/menu/img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.search_btn.setIcon(icon3)
        self.search_btn.setIconSize(QtCore.QSize(25, 25))
        self.search_btn.setCheckable(True)
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout_6.addWidget(self.search_btn)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_7.addItem(spacerItem)
        self.open_dir_btn = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.open_dir_btn.setFont(font)
        self.open_dir_btn.setStyleSheet(
            "QPushButton {\n"
            "    padding:10px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:1, y1:0.636, x2:0.369, y2:0.568455, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}"
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/menu/img/dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.open_dir_btn.setIcon(icon4)
        self.open_dir_btn.setIconSize(QtCore.QSize(25, 25))
        self.open_dir_btn.setObjectName("open_dir_btn")
        self.verticalLayout_7.addWidget(self.open_dir_btn)
        self.settings_btn = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.settings_btn.setFont(font)
        self.settings_btn.setStyleSheet(
            "QPushButton {\n"
            "    padding:10px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:1, y1:0.233, x2:0.358, y2:0.409364, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}\n"
            "QPushButton:checked {\n"
            "    background-color: qlineargradient(spread:pad, x1:1, y1:0.506045, x2:0.743545, y2:0.499, stop:0 rgba(130, 134, 156, 25), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}"
        )
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/menu/img/settings.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.settings_btn.setIcon(icon5)
        self.settings_btn.setIconSize(QtCore.QSize(25, 25))
        self.settings_btn.setCheckable(True)
        self.settings_btn.setObjectName("settings_btn")
        self.verticalLayout_7.addWidget(self.settings_btn)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.horizontalLayout_6.addWidget(self.menu_frame)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0.130682, x2:1, y2:0.75, stop:0 #232230, stop:1 #22212F);"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.preview = QtWidgets.QLabel(self.frame_3)
        self.preview.setMinimumSize(QtCore.QSize(60, 60))
        self.preview.setMaximumSize(QtCore.QSize(60, 60))
        self.preview.setStyleSheet("background-color: rgb(179, 179, 179);")
        self.preview.setObjectName("preview")
        self.horizontalLayout_5.addWidget(self.preview)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.book_name = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.book_name.setFont(font)
        self.book_name.setObjectName("book_name")
        self.verticalLayout_4.addWidget(self.book_name)
        self.book_author = QtWidgets.QLabel(self.frame_3)
        self.book_author.setObjectName("book_author")
        self.verticalLayout_4.addWidget(self.book_author)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_8.addWidget(self.frame_3)
        spacerItem2 = QtWidgets.QSpacerItem(
            155, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_8.addItem(spacerItem2)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.frame_4)
        self.widget.setMaximumSize(QtCore.QSize(600, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(
            150, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(24)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_60 = QtWidgets.QPushButton(self.widget)
        self.l_60.setStyleSheet(
            "QToolTip {\n"
            "    background-color: #313040;\n"
            "    padding: 2px;\n"
            "    border-radius: 3px;\n"
            "    opacity: 200;\n"
            "}"
        )
        self.l_60.setObjectName("l_60")
        self.horizontalLayout.addWidget(self.l_60)
        self.l_10 = QtWidgets.QPushButton(self.widget)
        self.l_10.setWhatsThis("")
        self.l_10.setStyleSheet(
            "QToolTip {\n"
            "    background-color: #313040;\n"
            "    padding: 2px;\n"
            "    border-radius: 3px;\n"
            "    opacity: 200;\n"
            "}"
        )
        self.l_10.setObjectName("l_10")
        self.horizontalLayout.addWidget(self.l_10)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.ps_btn = QtWidgets.QPushButton(self.widget)
        self.ps_btn.setObjectName("ps_btn")
        self.horizontalLayout_3.addWidget(self.ps_btn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.f_10 = QtWidgets.QPushButton(self.widget)
        self.f_10.setStyleSheet(
            "QToolTip {\n"
            "    background-color: #313040;\n"
            "    padding: 2px;\n"
            "    border-radius: 3px;\n"
            "    opacity: 200;\n"
            "}"
        )
        self.f_10.setObjectName("f_10")
        self.horizontalLayout_2.addWidget(self.f_10)
        self.f_60 = QtWidgets.QPushButton(self.widget)
        self.f_60.setStyleSheet(
            "QToolTip {\n"
            "    background-color: #313040;\n"
            "    padding: 2px;\n"
            "    border-radius: 3px;\n"
            "    opacity: 200;\n"
            "}"
        )
        self.f_60.setObjectName("f_60")
        self.horizontalLayout_2.addWidget(self.f_60)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(
            150, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.widget)
        self.time_slider = QtWidgets.QSlider(self.frame_4)
        self.time_slider.setMaximumSize(QtCore.QSize(600, 16777215))
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setObjectName("time_slider")
        self.verticalLayout_3.addWidget(self.time_slider)
        self.horizontalLayout_8.addWidget(self.frame_4)
        spacerItem5 = QtWidgets.QSpacerItem(
            156, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_8.addItem(spacerItem5)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.volume_btn = QtWidgets.QToolButton(self.frame_9)
        self.volume_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.volume_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.volume_btn.setMouseTracking(False)
        self.volume_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.volume_btn.setStyleSheet(
            "QToolButton {\n"
            "    border: none;\n"
            "    padding:10px;\n"
            "    background-color: rgba(255, 255, 255, 0);\n"
            "}\n"
            "QToolButton:hover:!pressed {\n"
            "    border: 0px solid;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.131, y1:0, x2:0.239, y2:0.278682, stop:0 rgba(130, 134, 156, 50), stop:1 rgba(130, 134, 156, 150));\n"
            "    border-radius: 10px;\n"
            "}"
        )
        self.volume_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/volume/img/max_volume.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.volume_btn.setIcon(icon6)
        self.volume_btn.setIconSize(QtCore.QSize(40, 40))
        self.volume_btn.setObjectName("volume_btn")
        self.horizontalLayout_7.addWidget(self.volume_btn)
        self.owerlay_btn = QtWidgets.QToolButton(self.frame_9)
        self.owerlay_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.owerlay_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.owerlay_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.owerlay_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.owerlay_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.owerlay_btn.setStyleSheet(
            "QToolButton {\n"
            "    border: none;\n"
            "    padding:10px;\n"
            "    background-color: rgba(255, 255, 255, 0);\n"
            "}\n"
            "QToolButton:hover:!pressed {\n"
            "    border: 0px solid;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.886, y1:0, x2:0.733, y2:0.312773, stop:0 rgba(130, 134, 156, 50), stop:1 rgba(130, 134, 156, 100));\n"
            "    border-radius: 10px;\n"
            "}\n"
            "QToolTip {\n"
            "    background-color: #313040;\n"
            "    padding: 2px;\n"
            "    border-radius: 3px;\n"
            "    opacity: 200;\n"
            "}"
        )
        self.owerlay_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(":/owerlay/img/owerlay.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.owerlay_btn.setIcon(icon7)
        self.owerlay_btn.setIconSize(QtCore.QSize(40, 40))
        self.owerlay_btn.setObjectName("owerlay_btn")
        self.horizontalLayout_7.addWidget(self.owerlay_btn)
        self.horizontalLayout_8.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_btn.setText(_translate("MainWindow", "   меню"))
        self.my_books_btn.setText(_translate("MainWindow", "   мои книги"))
        self.my_favorite_btn.setText(_translate("MainWindow", "   любимое"))
        self.search_btn.setText(_translate("MainWindow", "   поиск"))
        self.open_dir_btn.setText(_translate("MainWindow", "   папка с книгами"))
        self.settings_btn.setText(_translate("MainWindow", "   настройки"))
        self.preview.setText(_translate("MainWindow", "превью"))
        self.book_name.setText(_translate("MainWindow", "Название"))
        self.book_author.setText(_translate("MainWindow", "Автор"))
        self.l_60.setToolTip(_translate("MainWindow", "на 1 мин"))
        self.l_60.setText(_translate("MainWindow", "<<"))
        self.l_10.setToolTip(_translate("MainWindow", "на 10 сек"))
        self.l_10.setText(_translate("MainWindow", "<"))
        self.ps_btn.setText(_translate("MainWindow", "пауза"))
        self.f_10.setToolTip(_translate("MainWindow", "на 10 сек"))
        self.f_10.setText(_translate("MainWindow", ">"))
        self.f_60.setToolTip(_translate("MainWindow", "на 1 мин"))
        self.f_60.setText(_translate("MainWindow", ">>"))
        self.owerlay_btn.setToolTip(
            _translate("MainWindow", "Открыть поверх всех окон")
        )
