# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from . import icons_rc  # noqa
from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 631)
        font = QtGui.QFont()
        font.setPointSize(6)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(
            "background-color: rgb(32, 34, 37);\n" "color: #8E9297;"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "/*  BUTTONS */\n"
            "QPushButton {\n"
            "    border: 0px solid #000;\n"
            "    border-radius: 5px;    \n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    border-radius: 5px;    \n"
            "    background-color: #34373C;\n"
            "}\n"
            "QPushButton:pressed {    \n"
            "    background-color: #37393F;\n"
            "}\n"
            "\n"
            "/*  TOOLTIP */\n"
            "QToolTip {\n"
            "    background-color: #1D1E22;\n"
            "    border: none;\n"
            "    border-left: 2px solid #8E9297;\n"
            "    text-align: left;\n"
            "    padding: 4px;\n"
            "}\n"
            "\n"
            "/*  MENU */\n"
            "#menuFrame * {\n"
            "    text-align: left;\n"
            "}\n"
            "\n"
            "/*  CONTENT */\n"
            "#content {\n"
            "    border-top-left-radius: 15px;\n"
            "    background-color: rgb(54, 57, 63);\n"
            "}\n"
            "\n"
            "#content * {\n"
            "    background-color: rgb(54, 57, 63);\n"
            "}\n"
            "\n"
            "/*  CONTROL PANEL */\n"
            "#controlPanel, #controlPanel QFrame {\n"
            "    background-color: rgb(41, 43, 47);\n"
            "}\n"
            "\n"
            "\n"
            "/* SLIDER */\n"
            "QSlider {\n"
            "    background-color: rgb(41, 43, 47);\n"
            "}\n"
            "\n"
            "QSlider::groove:horizontal {\n"
            "    background: #40444B;\n"
            "    border-radius: 1px;\n"
            "}\n"
            "\n"
            "QSlider::sub-page:horizontal {\n"
            "    background: #8E9297;\n"
            "    border-radius: 1px;\n"
            "    height: 40px;\n"
            "}\n"
            "\n"
            "QSlider::add-page:horizontal {\n"
            "    background: #40444B;\n"
            "    border-radius: 1px;\n"
            "    height: 40px;\n"
            "}\n"
            "\n"
            "QSlider::handle:horizontal {\n"
            "    background: #8E9297;\n"
            "    border: 0px;\n"
            "    width: 8px;\n"
            "    margin-top: 0px;\n"
            "    margin-bottom: 0px;\n"
            "    border-radius: 1px;\n"
            "}\n"
            "\n"
            "\n"
            ""
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.topFrame = QtWidgets.QFrame(self.centralwidget)
        self.topFrame.setMinimumSize(QtCore.QSize(0, 28))
        self.topFrame.setMaximumSize(QtCore.QSize(16777215, 28))
        self.topFrame.setStyleSheet("")
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo = QtWidgets.QLabel(self.topFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setObjectName("logo")
        self.horizontalLayout_2.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(
            849, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.topBtnFrame = QtWidgets.QFrame(self.topFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topBtnFrame.sizePolicy().hasHeightForWidth())
        self.topBtnFrame.setSizePolicy(sizePolicy)
        self.topBtnFrame.setStyleSheet("")
        self.topBtnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBtnFrame.setObjectName("topBtnFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topBtnFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.topBtnFrame)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.minimizeAppBtn.setStyleSheet("")
        self.minimizeAppBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/other/dash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.minimizeAppBtn.setIcon(icon)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(14, 14))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout.addWidget(self.minimizeAppBtn)
        self.fullscreenAppBtn = QtWidgets.QPushButton(self.topBtnFrame)
        self.fullscreenAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.fullscreenAppBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.fullscreenAppBtn.setStyleSheet("")
        self.fullscreenAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/other/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.fullscreenAppBtn.setIcon(icon1)
        self.fullscreenAppBtn.setIconSize(QtCore.QSize(14, 14))
        self.fullscreenAppBtn.setObjectName("fullscreenAppBtn")
        self.horizontalLayout.addWidget(self.fullscreenAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.topBtnFrame)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.closeAppBtn.setStyleSheet("")
        self.closeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/other/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.closeAppBtn.setIcon(icon2)
        self.closeAppBtn.setIconSize(QtCore.QSize(14, 14))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout.addWidget(self.closeAppBtn)
        self.horizontalLayout_2.addWidget(self.topBtnFrame)
        self.verticalLayout_4.addWidget(self.topFrame)
        self.centralFrame = QtWidgets.QFrame(self.centralwidget)
        self.centralFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centralFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralFrame.setObjectName("centralFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menuFrame = QtWidgets.QFrame(self.centralFrame)
        self.menuFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.menuFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menuFrame.setStyleSheet("")
        self.menuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menuFrame)
        self.verticalLayout.setContentsMargins(5, 0, 8, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menuBtnsFrame = QtWidgets.QFrame(self.menuFrame)
        self.menuBtnsFrame.setStyleSheet(
            "QPushButton {\n"
            "    padding-top: 8px;\n"
            "    padding-bottom: 8px;\n"
            "    border: 0px solid #000;\n"
            "    border-radius: 5px;    \n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    border-radius: 5px;    \n"
            "    background-color: #34373C;\n"
            "}\n"
            "QPushButton:pressed {    \n"
            "    background-color: #37393F;\n"
            "}"
        )
        self.menuBtnsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuBtnsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuBtnsFrame.setObjectName("menuBtnsFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menuBtnsFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menuBtn = QtWidgets.QPushButton(self.menuBtnsFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.menuBtn.setFont(font)
        self.menuBtn.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/menu/hide_menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.menuBtn.setIcon(icon3)
        self.menuBtn.setIconSize(QtCore.QSize(25, 25))
        self.menuBtn.setObjectName("menuBtn")
        self.verticalLayout_3.addWidget(self.menuBtn)
        self.splitLine = QtWidgets.QFrame(self.menuBtnsFrame)
        self.splitLine.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splitLine.setObjectName("splitLine")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.splitLine)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(
            5, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.splitLine)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setStyleSheet(
            "background-color: rgb(45, 47, 50);\n"
            "border: 1px solid  rgb(45, 47, 50);\n"
            "border-radius: 2px;"
        )
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(
            5, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.splitLine)
        self.btnGroupFrame = QtWidgets.QFrame(self.menuBtnsFrame)
        self.btnGroupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnGroupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnGroupFrame.setObjectName("btnGroupFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.btnGroupFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.libraryBtn = QtWidgets.QPushButton(self.btnGroupFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.libraryBtn.setFont(font)
        self.libraryBtn.setStyleSheet("padding-left: 5px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/menu/book.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.libraryBtn.setIcon(icon4)
        self.libraryBtn.setIconSize(QtCore.QSize(25, 25))
        self.libraryBtn.setObjectName("libraryBtn")
        self.verticalLayout_2.addWidget(self.libraryBtn)
        self.favoriteBooksBtn = QtWidgets.QPushButton(self.btnGroupFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.favoriteBooksBtn.setFont(font)
        self.favoriteBooksBtn.setStyleSheet("padding-left: 5px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/menu/star.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.favoriteBooksBtn.setIcon(icon5)
        self.favoriteBooksBtn.setIconSize(QtCore.QSize(25, 25))
        self.favoriteBooksBtn.setObjectName("favoriteBooksBtn")
        self.verticalLayout_2.addWidget(self.favoriteBooksBtn)
        self.searchBookBtn = QtWidgets.QPushButton(self.btnGroupFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.searchBookBtn.setFont(font)
        self.searchBookBtn.setStyleSheet("padding-left: 5px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/menu/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.searchBookBtn.setIcon(icon6)
        self.searchBookBtn.setIconSize(QtCore.QSize(25, 25))
        self.searchBookBtn.setObjectName("searchBookBtn")
        self.verticalLayout_2.addWidget(self.searchBookBtn)
        self.verticalLayout_3.addWidget(self.btnGroupFrame)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 326, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_3.addItem(spacerItem3)
        self.btnGroupFrame_2 = QtWidgets.QFrame(self.menuBtnsFrame)
        self.btnGroupFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnGroupFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnGroupFrame_2.setObjectName("btnGroupFrame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.btnGroupFrame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dirWithBooksBtn = QtWidgets.QPushButton(self.btnGroupFrame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dirWithBooksBtn.setFont(font)
        self.dirWithBooksBtn.setStyleSheet("padding-left: 5px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(":/menu/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.dirWithBooksBtn.setIcon(icon7)
        self.dirWithBooksBtn.setIconSize(QtCore.QSize(25, 25))
        self.dirWithBooksBtn.setObjectName("dirWithBooksBtn")
        self.verticalLayout_5.addWidget(self.dirWithBooksBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.btnGroupFrame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.settingsBtn.setFont(font)
        self.settingsBtn.setStyleSheet("padding-left: 5px;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(":/menu/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.settingsBtn.setIcon(icon8)
        self.settingsBtn.setIconSize(QtCore.QSize(25, 25))
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_5.addWidget(self.settingsBtn)
        self.verticalLayout_3.addWidget(self.btnGroupFrame_2)
        self.verticalLayout.addWidget(self.menuBtnsFrame)
        self.horizontalLayout_3.addWidget(self.menuFrame)
        self.contentBox = QtWidgets.QFrame(self.centralFrame)
        self.contentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.content = QtWidgets.QFrame(self.contentBox)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.libraryPage = QtWidgets.QWidget()
        self.libraryPage.setObjectName("libraryPage")
        self.stackedWidget.addWidget(self.libraryPage)
        self.favoritBooksPage = QtWidgets.QWidget()
        self.favoritBooksPage.setObjectName("favoritBooksPage")
        self.stackedWidget.addWidget(self.favoritBooksPage)
        self.searchBookPage = QtWidgets.QWidget()
        self.searchBookPage.setObjectName("searchBookPage")
        self.stackedWidget.addWidget(self.searchBookPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.stackedWidget.addWidget(self.settingsPage)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_7.addWidget(self.content)
        self.controlPanel = QtWidgets.QFrame(self.contentBox)
        self.controlPanel.setMinimumSize(QtCore.QSize(0, 75))
        self.controlPanel.setMaximumSize(QtCore.QSize(16777215, 75))
        self.controlPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlPanel.setObjectName("controlPanel")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.controlPanel)
        self.horizontalLayout_7.setContentsMargins(5, 6, 5, 5)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bookPreview = QtWidgets.QFrame(self.controlPanel)
        self.bookPreview.setMinimumSize(QtCore.QSize(150, 60))
        self.bookPreview.setMaximumSize(QtCore.QSize(340, 60))
        self.bookPreview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bookPreview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bookPreview.setObjectName("bookPreview")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bookPreview)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bookCover = QtWidgets.QLabel(self.bookPreview)
        self.bookCover.setMinimumSize(QtCore.QSize(60, 60))
        self.bookCover.setMaximumSize(QtCore.QSize(60, 60))
        self.bookCover.setStyleSheet("background-color: rgb(130, 130, 130);")
        self.bookCover.setText("")
        self.bookCover.setObjectName("bookCover")
        self.horizontalLayout_6.addWidget(self.bookCover)
        self.bookTitle = QtWidgets.QFrame(self.bookPreview)
        self.bookTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.bookTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bookTitle.setStyleSheet("")
        self.bookTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bookTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bookTitle.setObjectName("bookTitle")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.bookTitle)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bookNameLabel = QtWidgets.QLabel(self.bookTitle)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bookNameLabel.setFont(font)
        self.bookNameLabel.setObjectName("bookNameLabel")
        self.verticalLayout_6.addWidget(self.bookNameLabel)
        self.bookAuthorLabel = QtWidgets.QLabel(self.bookTitle)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bookAuthorLabel.setFont(font)
        self.bookAuthorLabel.setObjectName("bookAuthorLabel")
        self.verticalLayout_6.addWidget(self.bookAuthorLabel)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_6.addWidget(self.bookTitle)
        self.horizontalLayout_7.addWidget(self.bookPreview)
        self.playPauseBtn = QtWidgets.QPushButton(self.controlPanel)
        self.playPauseBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.playPauseBtn.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.playPauseBtn.setFont(font)
        self.playPauseBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap(":/other/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.playPauseBtn.setIcon(icon9)
        self.playPauseBtn.setIconSize(QtCore.QSize(40, 40))
        self.playPauseBtn.setObjectName("playPauseBtn")
        self.horizontalLayout_7.addWidget(self.playPauseBtn)
        spacerItem5 = QtWidgets.QSpacerItem(
            674, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_7.addItem(spacerItem5)
        self.toolsFrame = QtWidgets.QFrame(self.controlPanel)
        self.toolsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolsFrame.setObjectName("toolsFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.toolsFrame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.speedBox = QtWidgets.QFrame(self.toolsFrame)
        self.speedBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.speedBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.speedBox.setObjectName("speedBox")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.speedBox)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.speedBtn = QtWidgets.QPushButton(self.speedBox)
        self.speedBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.speedBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.speedBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap(":/other/watch.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.speedBtn.setIcon(icon10)
        self.speedBtn.setIconSize(QtCore.QSize(28, 28))
        self.speedBtn.setObjectName("speedBtn")
        self.horizontalLayout_11.addWidget(self.speedBtn)
        self.speedFrame = QtWidgets.QFrame(self.speedBox)
        self.speedFrame.setMaximumSize(QtCore.QSize(0, 16777215))
        self.speedFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.speedFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.speedFrame.setObjectName("speedFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.speedFrame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.speedSlider = QtWidgets.QSlider(self.speedFrame)
        self.speedSlider.setMinimumSize(QtCore.QSize(80, 35))
        self.speedSlider.setMaximumSize(QtCore.QSize(80, 35))
        self.speedSlider.setStyleSheet("")
        self.speedSlider.setMaximum(100)
        self.speedSlider.setProperty("value", 50)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.horizontalLayout_12.addWidget(self.speedSlider)
        self.speedLabel = QtWidgets.QLabel(self.speedFrame)
        self.speedLabel.setObjectName("speedLabel")
        self.horizontalLayout_12.addWidget(self.speedLabel)
        self.horizontalLayout_11.addWidget(self.speedFrame)
        self.horizontalLayout_8.addWidget(self.speedBox)
        self.volumeBox = QtWidgets.QFrame(self.toolsFrame)
        self.volumeBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.volumeBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.volumeBox.setObjectName("volumeBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.volumeBox)
        self.horizontalLayout_10.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.volumeBtn = QtWidgets.QPushButton(self.volumeBox)
        self.volumeBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.volumeBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.volumeBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap(":/volume/medium_volume.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.volumeBtn.setIcon(icon11)
        self.volumeBtn.setIconSize(QtCore.QSize(28, 28))
        self.volumeBtn.setObjectName("volumeBtn")
        self.horizontalLayout_10.addWidget(self.volumeBtn)
        self.volumeFrame = QtWidgets.QFrame(self.volumeBox)
        self.volumeFrame.setMaximumSize(QtCore.QSize(0, 16777215))
        self.volumeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.volumeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.volumeFrame.setObjectName("volumeFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.volumeFrame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.volumeSlider = QtWidgets.QSlider(self.volumeFrame)
        self.volumeSlider.setMinimumSize(QtCore.QSize(80, 35))
        self.volumeSlider.setMaximumSize(QtCore.QSize(80, 35))
        self.volumeSlider.setStyleSheet("")
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 50)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_9.addWidget(self.volumeSlider)
        self.volumeLabel = QtWidgets.QLabel(self.volumeFrame)
        self.volumeLabel.setObjectName("volumeLabel")
        self.horizontalLayout_9.addWidget(self.volumeLabel)
        self.horizontalLayout_10.addWidget(self.volumeFrame)
        self.horizontalLayout_8.addWidget(self.volumeBox)
        self.overlayBtn = QtWidgets.QPushButton(self.toolsFrame)
        self.overlayBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.overlayBtn.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.overlayBtn.setFont(font)
        self.overlayBtn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(
            QtGui.QPixmap(":/other/overlay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.overlayBtn.setIcon(icon12)
        self.overlayBtn.setIconSize(QtCore.QSize(28, 28))
        self.overlayBtn.setObjectName("overlayBtn")
        self.horizontalLayout_8.addWidget(self.overlayBtn)
        self.horizontalLayout_7.addWidget(self.toolsFrame)
        self.verticalLayout_7.addWidget(self.controlPanel)
        self.horizontalLayout_3.addWidget(self.contentBox)
        self.verticalLayout_4.addWidget(self.centralFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "AB Player"))
        self.menuBtn.setText(_translate("MainWindow", " Скрыть меню"))
        self.libraryBtn.setText(_translate("MainWindow", " Мои книги"))
        self.favoriteBooksBtn.setText(_translate("MainWindow", " Любимое"))
        self.searchBookBtn.setText(_translate("MainWindow", " Поиск"))
        self.dirWithBooksBtn.setText(_translate("MainWindow", " Папка с книгами"))
        self.settingsBtn.setText(_translate("MainWindow", " Настройки"))
        self.bookNameLabel.setText(_translate("MainWindow", "Название"))
        self.bookAuthorLabel.setText(_translate("MainWindow", "Автор"))
        self.speedBtn.setToolTip(_translate("MainWindow", "Скорость воспроизведения"))
        self.speedLabel.setText(_translate("MainWindow", "50%"))
        self.volumeBtn.setToolTip(_translate("MainWindow", "Громкость"))
        self.volumeLabel.setText(_translate("MainWindow", "50%"))
        self.overlayBtn.setToolTip(_translate("MainWindow", "Открыть поверх всех окон"))
